import os
import csv
import xlsxwriter

os.makedirs("sales", exist_ok=True)

csv_path = os.path.join("sales", "LeadNet_Hitlist_Pipeline.csv")
xlsx_paths = [
    os.path.join("sales", "LeadNet_Verified_DBPR_Hitlist.xlsx"),
    os.path.join("sales", "LeadNet_Sponsored_Hitlist.xlsx"),
    os.path.join("sales", "LeadNet_Hitlist_Pipeline.xlsx"),
]

headers = [
    "Status",
    "Priority Tier",
    "Company Name",
    "Trade",
    "City / Metro",
    "Store / Operating Hours",
    "Verified Licensee / Owner (DBPR & Sunbiz)",
    "State License # (CAC / CFC / CMC)",
    "Direct / Cell Phone",
    "Office / LSA Phone",
    "Email",
    "Website",
    "Running Google Ads?",
    "Google Rating / Reviews",
    "Speed to Lead Hook / Paid Ad Pain Point",
    "Dial 1 Outcome",
    "Dial 2 Outcome",
    "Demo Booked Date",
    "Est. System Value",
    "Notes / Next Action",
]

# Verified Florida Contractor Hitlist (Under 1k reviews sweet spot)
# Verified via Florida DBPR (myfloridalicense.com) & Sunbiz (sunbiz.org)
companies_data = [
    # 1. English Air Inc.
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "English Air Inc.",
        "HVAC",
        "Orlando, FL",
        "Closes 6:00 PM",
        "Anton O. Martin (President / Primary Qualifier)",
        "CMC1249480",
        "(407) 468-7808",
        "(407) 468-7808",
        "info@englishairinc.com",
        "https://englishairinc.com",
        "Yes (Sponsored)",
        "4.8 (416 reviews)",
        "Running Google sponsored ads. Closes 6 PM daily. Misses emergency evening calls while paying top CPC for ad clicks.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Anton Martin: 'Hey Anton, saw your sponsored Google ad in Orlando—we turn your after-6pm missed calls into booked morning jobs.'",
    ],
    # 2. Air Care
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Air Care (Air Care Heating & Cooling)",
        "HVAC",
        "Longwood / Orlando, FL",
        "Closes 8:00 PM",
        "Ian Chaves (Manager) / Joseph P. Cacioppo",
        "CAC1819812",
        "(407) 479-7197",
        "(407) 479-7197",
        "service@aircarecentralfl.com",
        "https://aircarecentralfl.com",
        "Yes (Sponsored)",
        "4.8 (225 reviews)",
        "Sponsored Google ad running. Closes at 8 PM. Unanswered late-night emergency replacement calls bleed to competitors.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Ian Chaves: 'Hey Ian, regarding your sponsored ad—we catch every missed dial within 3 seconds with an instant priority intake.'",
    ],
    # 3. Elevate Air Conditioning & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Elevate Air Conditioning & Heating LLC",
        "HVAC",
        "Apopka, FL",
        "Open 24 Hours",
        "Shelby Martin (Manager) / Nick Fleshman",
        "CAC1822450",
        "(407) 974-6494",
        "(407) 974-6494",
        "info@elevateairfl.com",
        "https://elevateairfl.com",
        "Yes",
        "4.9 (250 reviews)",
        "7+ years in business, 24/7 service. Peak dispatch call overflow needs instant customer recovery before they call the next listing.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Shelby or Nick: 'Hey Shelby, we help Apopka contractors lock down emergency AC replacements in under 3 seconds.'",
    ],
    # 4. AC2 HVAC Services Inc
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "AC2 HVAC Services Inc",
        "HVAC",
        "Apopka, FL",
        "Closes 5:00 PM",
        "Justin R. Smith (President) / Rosa M. Cortes (VP)",
        "CAC1821815",
        "(407) 561-7036",
        "(407) 561-7036",
        "service@ac2hvac.com",
        "https://ac2hvac.com",
        "Yes",
        "4.9 (396 reviews)",
        "5+ years in business. Closes 5 PM daily. Homeowners calling between 5 PM and 9 PM currently receive voicemail instead of instant text.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Justin Smith: 'Hey Justin, saw you close at 5 PM in Apopka—we capture all your evening emergency HVAC calls automatically.'",
    ],
    # 5. K&E A/C and Refrigeration
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "K&E A/C and Refrigeration, Inc.",
        "HVAC / Refrigeration",
        "Apopka, FL",
        "Closes 10:00 PM",
        "Kevin O'Neill / Edwin Ortiz (Qualifiers)",
        "CAC1821597",
        "(407) 232-5112",
        "(407) 232-5112",
        "info@kandeac.com",
        "https://www.kandeac.com",
        "Yes",
        "5.0 (275 reviews)",
        "5.0 rating with 275 reviews. High growth shop prime for RevSurge database reactivation and instant missed-call safety net.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Kevin or Edwin: 'Hey Kevin, you have 275 5-star reviews—we can reactivate your past customer database into $20k+ in tune-up swaps.'",
    ],
    # 6. Complete Air Solutions
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Complete Air Solutions LLC",
        "HVAC",
        "Apopka, FL",
        "Closes 7:00 PM",
        "Antonio Rivera (Owner) / Jacklyn Aviles-Rivera",
        "CAC1814761",
        "(321) 207-6394",
        "(321) 207-6394",
        "info@completeairsolutionsfl.com",
        "https://completeairsolutionsfl.com",
        "Yes",
        "4.9 (413 reviews)",
        "10+ years in business. Closes 7 PM. Automated text back captures after-hours quote requests and emergency service calls.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Antonio Rivera: 'Hey Antonio, pitch instant missed-call recovery for your Apopka service territory.'",
    ],
    # 7. ACR Air Conditioning & Refrigeration
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "ACR Air Conditioning & Refrigeration",
        "HVAC / Refrigeration",
        "Apopka, FL",
        "Open 24 Hours",
        "Mark R. Ruggiero / Frank Ruggiero (Qualifiers)",
        "CAC058474",
        "(407) 449-8679",
        "(407) 449-8679",
        "service@callacr.com",
        "https://callacr.com",
        "Yes",
        "4.9 (871 reviews)",
        "40+ years in business, 871 reviews. 24/7 emergency dispatch—instant tech alert + intake routing saves CSR overhead.",
        "",
        "",
        "",
        "$8,500",
        "Ask for Mark Ruggiero: 'Hey Mark, with your call volume, our LiveWire tech alert system catches 10-15 dropped leads a week.'",
    ],
    # 8. All-Star Heating and Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "All-Star Heating and Air Conditioning LLC",
        "HVAC",
        "Apopka, FL",
        "Closes 6:00 PM",
        "Javier Rosado / Carlos Rosado (Owners / Qualifiers)",
        "CAC1820980",
        "(352) 638-3075",
        "(352) 638-3075",
        "service@allstarhvacfl.com",
        "https://allstarhvacfl.com",
        "Yes",
        "4.9 (96 reviews)",
        "Closes 6 PM. Sweet-spot owner operator (96 reviews). Needs review boost to cross 200+ & missed-call capture.",
        "",
        "",
        "",
        "$6,500",
        "Ask for Javier: Pitch automatic Google Review generation + sub-3-second missed-call text back.",
    ],
    # 9. AC's Heating & Air LLC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "AC's Heating & Air LLC",
        "HVAC",
        "Apopka / Orlando, FL",
        "Open 24 Hours",
        "Allen H. Chennault (President / Qualifier)",
        "CAC1818233",
        "(407) 440-0105",
        "(407) 440-0105",
        "service@callacs.com",
        "https://callacs.com",
        "Yes",
        "4.8 (115 reviews)",
        "10+ years in business. 24/7 service. Open LSA advertiser losing ad clicks on busy signals when lines are tied up.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Allen Chennault: 'Hey Allen, we help 24/7 HVAC owners catch callers who hang up when the phone is busy.'",
    ],
    # 10. One Stop Air Mechanical
    [
        "Gatekeeper / Callback",
        "A - High (Sweet Spot / Fast Conversion)",
        "One Stop Air Mechanical",
        "HVAC",
        "Apopka / Orlando, FL",
        "Open 24 Hours",
        "Sergio Rosas (President / Owner)",
        "CAC1821045",
        "(689) 331-0895",
        "(689) 331-0895",
        "service@onestopairmechanical.com",
        "https://www.onestopairmechanical.com",
        "Yes",
        "5.0 (21 reviews)",
        "20+ reviews, active Google ads. Fast-growing shop needing automated speed-to-lead.",
        "Called 8/22: Gatekeeper took message, said she'd pass to Sergio/boss. 24h passed with no callback.",
        "",
        "",
        "$6,000",
        "FOLLOW UP: 'Hey, checking back in for Sergio on that emergency text setup before I close the file.'",
    ],
    # 11. Blue Star Air Conditioning LLC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Blue Star Air Conditioning LLC",
        "HVAC",
        "Longwood, FL",
        "Closes 6:30 PM",
        "Sanjay Baburao Patange (Primary Qualifier / Manager)",
        "CAC1816033",
        "(321) 204-0794",
        "(321) 204-0794",
        "info@bluestarairfl.com",
        "https://bluestarairfl.com",
        "Yes",
        "4.9 (698 reviews)",
        "Closes 6:30 PM. 15+ years in business. High ad spend across Seminole/Orange County. Recovers abandoned ad clicks.",
        "",
        "",
        "",
        "$8,500",
        "Ask for Sanjay Patange: 'Hey Sanjay, saw your Longwood team running ads—we stop paid lead bleed with instant 3-second text recovery.'",
    ],
    # 12. Nicks Air Conditioning & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Nicks Air Conditioning & Heating",
        "HVAC",
        "Apopka, FL",
        "Closes 5:00 PM",
        "Nickolas M. Ramos (Owner / Primary Qualifier)",
        "CAC1817219",
        "(407) 489-5060",
        "(407) 489-5060",
        "service@nicksacandheat.com",
        "https://www.nicksacandheat.com",
        "Yes",
        "4.7 (187 reviews)",
        "Closes 5 PM. 38+ years trade experience. Emergency weekend/evening calls go straight to voicemail.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Nick Ramos: 'Hey Nick, we turn after-hours voicemails in Apopka into signed emergency changeouts before morning.'",
    ],
    # 13. Cee Bee Air Systems
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Cee Bee Air Systems, Inc",
        "HVAC",
        "Apopka, FL",
        "Closes 5:00 PM",
        "Phillip A. Blodgett (President / Primary Qualifier)",
        "CAC039747",
        "(407) 886-7046",
        "(407) 886-5960",
        "info@ceebeeair.com",
        "https://ceebeeair.com",
        "Yes",
        "4.9 (96 reviews)",
        "Closes 5 PM. 45+ years legacy brand. After-hours callers praised callback—automate that in 3 seconds.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Phillip Blodgett: 'Hey Phillip, saw your customer reviews praising your after-hours callbacks—we automate that instantly.'",
    ],
    # 14. All Star Heating and Cooling of Central FL
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "All Star Heating and Cooling of Central Florida, LLC",
        "HVAC",
        "Mt Dora, FL",
        "Closes 5:00 PM",
        "David M. Rivera / William Rodriguez (Managers)",
        "CAC1816824",
        "(407) 255-7827",
        "(407) 255-7827",
        "office@allstarcentralflorida.com",
        "https://allstarcentralflorida.com",
        "Yes",
        "4.8 (249 reviews)",
        "Closes 5 PM. 10+ years in business. Strong Lake County coverage missing late afternoon emergency dials.",
        "",
        "",
        "",
        "$7,500",
        "Ask for David Rivera: 'Hey David, we capture Lake County emergency AC replacements that call after 5 PM.'",
    ],
    # 15. D-Air solutions
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "D-Air solutions",
        "HVAC / Repair",
        "Apopka, FL",
        "Open 24 Hours",
        "Danilo De Souza (Owner / Operator)",
        "CAC1823104",
        "(929) 530-4739",
        "(929) 530-4739",
        "contact@d-airsolutions.com",
        "https://d-airsolutions.com",
        "Yes",
        "5.0 (13 reviews)",
        "24/7 service. Brand new 5.0-star operation. Needs review automation + instant missed-call capture.",
        "",
        "",
        "",
        "$5,500",
        "Ask for Danilo: 'Hey Danilo, we help new 5-star AC companies in Apopka scale their review volume and catch every caller.'",
    ],
    # 16. Orlando HVAC Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Orlando HVAC Air Conditioning",
        "HVAC",
        "Orlando, FL",
        "Closes 8:00 PM",
        "Robert L. Miller (Primary Qualifier)",
        "CAC1815120",
        "(689) 698-5010",
        "(689) 698-5010",
        "info@orlandohvacfl.com",
        "https://orlandohvacfl.com",
        "Yes",
        "4.9 (239 reviews)",
        "Closes 8 PM. 40+ years in trade. Prime candidate for customer database reactivation special.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Robert: 'Hey Robert, we extract $15k–$25k in booked maintenance from past Orlando customer databases.'",
    ],
    # 17. Allen's Refrigeration & Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Allen's Refrigeration & Air Conditioning Service, Inc.",
        "HVAC / Refrigeration",
        "Mt Dora, FL",
        "Closes 5:00 PM",
        "Brandon A. Hamlin (President) / Bradley A. Hamlin (VP)",
        "CAC1814675",
        "(352) 383-4998",
        "(407) 889-2021",
        "service@allens-ac.com",
        "https://allens-ac.com",
        "Yes",
        "5.0 (810 reviews)",
        "Closes 5 PM. 810 5-star reviews. Massive past customer base ready for RevSurge seasonal AC maintenance drips.",
        "",
        "",
        "",
        "$9,000",
        "Ask for Brandon or Bradley Hamlin: 'Hey Brandon, you have 800+ 5-star reviews—we can launch a safe 10DLC reactivation campaign to your list.'",
    ],
    # 18. Justice Air Conditioning Repair
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Justice Air Conditioning Repair LLC",
        "HVAC",
        "Longwood, FL",
        "Closes 5:00 PM",
        "Brad Justice (Owner / Qualifying Contractor)",
        "CAC1817540",
        "(407) 907-2110",
        "(407) 907-2110",
        "brad@justiceairconditioning.com",
        "https://justiceairconditioning.com",
        "Yes",
        "5.0 (545 reviews)",
        "Closes 5 PM. 545 reviews. Carrier factory trained background. Needs evening call capture & dispatch alert.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Brad Justice: 'Hey Brad, saw you close at 5 in Longwood—we catch all after-hours Carrier changeout inquiries instantly.'",
    ],
    # 19. TIKI 24/7 Heating & AC (Wilco AC)
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "TIKI 24/7 Heating and Air Conditioning (by Wilco AC)",
        "HVAC",
        "Longwood / Sanford, FL",
        "Open 24 Hours",
        "Wilson E. Correa (President / Qualifier)",
        "CAC1819665",
        "(407) 302-2982",
        "(407) 302-2982",
        "info@wilcohvac.com",
        "https://wilcohvac.com",
        "Yes (Sponsored)",
        "5.0 (44 reviews)",
        "Sponsored Google ad. 24/7 family-owned. Paying per click on Google while competitors steal missed calls.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Wilson Correa: 'Hey Wilson, saw your sponsored TIKI AC ad—we ensure every ad dollar results in an instant 3-second text.'",
    ],
    # 20. Air Tech of Central Florida
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Air Tech of Central Florida",
        "HVAC",
        "Longwood, FL",
        "Closes 10:00 PM",
        "Craig C. Baker / Scott Baker (Qualifiers / Officers)",
        "CAC058473",
        "(321) 244-6998",
        "(321) 244-6998",
        "service@airtechfl.com",
        "https://airtechfl.com",
        "Yes",
        "4.9 (946 reviews)",
        "Closes 10 PM. 25+ years in business. 946 reviews. Ideal mid-tier shop with heavy phone volume.",
        "",
        "",
        "",
        "$9,500",
        "Ask for Craig or Scott: 'Hey Craig, with 900+ reviews in Longwood, our LiveWire system recovers $20k/mo in abandoned ad dials.'",
    ],
    # 21. Nathan HVAC Contractors
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Nathan HVAC Contractors (Nath Air Plus LLC)",
        "HVAC",
        "Wekiwa Springs / Orlando, FL",
        "Closes 8:00 PM",
        "Yokaram Gopaul Nath (Owner / Primary Qualifier)",
        "CAC1820555",
        "(689) 331-8237",
        "(689) 331-8237",
        "info@nathairplus.com",
        "https://nathairplus.com",
        "Yes",
        "5.0 (69 reviews)",
        "Closes 8 PM. 10+ years experience. Sweet spot operator needing instant priority intake link on missed calls.",
        "",
        "",
        "",
        "$6,500",
        "Ask for Yokaram Nath: 'Hey Yokaram, we help Wekiwa Springs HVAC operators catch missed emergency calls on the first ring.'",
    ],
    # 22. Titan Air Conditioning & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Titan Air Conditioning & Heating LLC",
        "HVAC",
        "Winter Garden, FL",
        "Closes 5:00 PM",
        "Jason Kyle Tiner (President / Qualifier)",
        "CAC1820353",
        "(407) 296-9622",
        "(407) 296-9622",
        "service@titanairconditioningandheating.com",
        "https://titanairconditioningandheating.com",
        "Yes",
        "4.9 (263 reviews)",
        "Closes 5 PM. 263 reviews. Same-day emergency claim. Recover high-ticket AC swap leads after 5 PM.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Jason Tiner: 'Hey Jason, saw your same-day promise in Winter Garden—we catch after-5pm emergency replacements instantly.'",
    ],
    # 23. Sky Air LLC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Sky Air LLC",
        "HVAC",
        "Winter Park, FL",
        "Closes 5:00 PM",
        "John Perez (Manager / Owner)",
        "CAC1817429",
        "(407) 622-1725",
        "(407) 622-1725",
        "info@skyairandheat.com",
        "https://skyairandheat.com",
        "Yes",
        "4.9 (63 reviews)",
        "Closes 5 PM. 10+ years in trade. High response speed focus—LeadNet gives him sub-3-second automated intake.",
        "",
        "",
        "",
        "$6,500",
        "Ask for John Perez: 'Hey John, saw you service Winter Park and Orlando—we make your emergency text response under 3 seconds.'",
    ],
    # 24. Benzah Vent Cleaning LLC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Benzah Vent Cleaning LLC (Benzah Services)",
        "HVAC / Duct Cleaning",
        "Apopka, FL",
        "Open 24 Hours",
        "Anthony Gomez (Manager / Owner)",
        "CAC1822180",
        "(407) 865-3295",
        "(407) 865-3295",
        "customercare@benzahdvc.com",
        "https://benzahdvc.com",
        "Yes",
        "4.9 (252 reviews)",
        "24/7 service. Cross-sells duct cleaning & AC replacement. Drip reactivation will yield $15k+ from past duct customers.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Anthony Gomez: 'Hey Anthony, we can reactivate your past duct cleaning customer list into booked AC tune-up changeouts.'",
    ],
    # 25. ISS Mechanical
    [
        "Not Contacted",
        "B - Medium (Commercial / Multi-Tech)",
        "ISS Mechanical",
        "HVAC / Mechanical / Plumbing",
        "Apopka, FL",
        "Closes 5:00 PM",
        "Richard A. Bodwell (Owner / President)",
        "CMC1250294",
        "(813) 283-2545",
        "(407) 880-9999",
        "info@issmechanical.com",
        "https://issmechanical.com",
        "Yes",
        "4.4 (22 reviews)",
        "Closes 5 PM. Commercial & high-end residential mechanical. High ticket replacements ($12k+ avg).",
        "",
        "",
        "",
        "$12,000",
        "Ask for Richard Bodwell: 'Hey Richard, our LiveWire module provides real-time emergency tech alerts for commercial accounts.'",
    ],
    # 26. Team Air Conditioning & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Team Air Conditioning & Heating Inc.",
        "HVAC",
        "Sorrento / Ocoee, FL",
        "Closes 7:00 PM",
        "Hollis L. Hamilton (President / Primary Qualifier)",
        "CAC1814640",
        "(407) 395-3031",
        "(407) 395-3031",
        "info@teamairconditioning.com",
        "https://teamairconditioning.com",
        "Yes",
        "4.8 (165 reviews)",
        "Closes 7 PM. Lake & Orange County contractor. Missed calls go unmonitored during evening installs.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Hollis: 'Hey Hollis, we help Sorrento and Ocoee contractors capture emergency calls while techs are on ladders.'",
    ],
    # 27. ASR Services
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "ASR Services - Heating & Air Conditioning",
        "HVAC",
        "Ocoee, FL",
        "Closes 5:00 PM",
        "Garth Johnson (Founder) / Javon Johnson (VP)",
        "CAC1821996",
        "(321) 450-7491",
        "(407) 905-3660",
        "info@asrhvacservices.com",
        "https://asrhvacservices.com",
        "Yes",
        "5.0 (191 reviews)",
        "Closes 5 PM. 20+ years family-owned. Rapid response pitch to lock in first-slot morning appointments.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Javon Johnson: 'Hey Javon, saw your 5-star team in Ocoee—we help you lock in morning first-slot jobs from evening missed calls.'",
    ],
    # 28. AmeriTech Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "AmeriTech Air Conditioning and Heating",
        "HVAC",
        "Orlando, FL",
        "Closes 7:00 PM",
        "Brian T. Novotny (President / Qualifier)",
        "CAC1816358",
        "(407) 532-8000",
        "(407) 532-8000",
        "service@ameritechac.com",
        "https://ameritechac.com",
        "Yes",
        "4.6 (506 reviews)",
        "Closes 7 PM. 15+ years in business. 506 reviews. Boost review score to 4.8+ and stop missed ad call leak.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Brian Novotny: 'Hey Brian, we combine automated 5-star Google review collection with instant missed call text-back.'",
    ],
    # 29. All Cool Heat Plumbing & GC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "All Cool Heat Plumbing & General Contractor Inc",
        "HVAC / Plumbing / GC",
        "Apopka, FL",
        "Open 24 Hours",
        "Jorge L. Rodriguez (President / Triple License Qualifier)",
        "CAC1814990",
        "(407) 461-0301",
        "(407) 461-0301",
        "contact@certifiedquality.org",
        "https://www.certifiedquality.org",
        "Yes",
        "4.5 (28 reviews)",
        "24/7 service. Multi-trade operator. Triple revenue potential across HVAC, plumbing, and tenant buildout.",
        "",
        "",
        "",
        "$9,000",
        "Ask for Jorge Rodriguez: 'Hey Jorge, we capture emergency plumbing and AC inquiries across Apopka with custom trade routing.'",
    ],
    # 30. Apopka Heating And AC Repair
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Apopka Heating And Air Conditioning Repair Service",
        "HVAC",
        "Apopka, FL",
        "Closes 9:00 PM",
        "Eric D. Gonzalez (Manager / Qualifier)",
        "CAC1819512",
        "(407) 565-2545",
        "(407) 565-2545",
        "info@apopkaheatandair.com",
        "https://apopkaheatandair.com",
        "Yes",
        "3.3 (14 reviews)",
        "Closes 9 PM. 3.3 rating is killing conversion on search. Needs automated 5-star Google review drip module.",
        "",
        "",
        "",
        "$6,000",
        "Ask for Eric: 'Hey Eric, we can get your Google rating from 3.3 to 4.5+ using automated review requests after service.'",
    ],
    # 31. Cuban Air Conditioning & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Cuban Air Conditioning & Heating LLC",
        "HVAC",
        "Altamonte Springs, FL",
        "Closes 10:00 PM",
        "Eduardo 'Eddy' Hernandez (Manager / Lead Qualifier)",
        "CAC1822814",
        "(786) 602-8246",
        "(786) 602-8246",
        "service@cubanairconditioning.com",
        "https://cubanairconditioning.com",
        "Yes",
        "5.0 (110 reviews)",
        "Closes 10 PM. 110 5-star reviews. High personal responsiveness—LeadNet secures his speed-to-lead advantage.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Eddy: 'Oye Eddy, saw your 110 5-star reviews in Altamonte—we make sure you never miss an emergency AC client.'",
    ],
    # 32. Summit Peak HVAC Solutions
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Summit Peak HVAC Solutions",
        "HVAC",
        "Orlando / Apopka, FL",
        "Open 24 Hours",
        "Brandon M. Clark (Owner / Qualifier)",
        "CAC1823410",
        "(929) 662-6047",
        "(929) 662-6047",
        "info@summitpeakhvac.com",
        "https://summitpeakhvac.com",
        "Yes",
        "4.8 (16 reviews)",
        "24/7 emergency response. Early stage shop needing automated client intake and review acceleration.",
        "",
        "",
        "",
        "$5,500",
        "Ask for Brandon Clark: Pitch automated priority intake form + 3-second missed call rescue.",
    ],
    # 33. Certified AC Services
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Certified AC Services (Certified Mechanical Co)",
        "HVAC",
        "Apopka, FL",
        "Closes 5:00 PM",
        "Michael J. Peters (Primary Qualifier / President)",
        "CAC1816190",
        "(407) 294-6324",
        "(407) 294-6324",
        "info@certifiedacservicesfl.com",
        "https://certifiedacservicesfl.com",
        "Yes",
        "4.5 (24 reviews)",
        "Closes 5 PM. 15+ years in business. Small crew losing late afternoon homeowner calls.",
        "",
        "",
        "",
        "$6,500",
        "Ask for Michael Peters: 'Hey Michael, we capture emergency HVAC inquiries in Apopka when your phone goes to voicemail after 5.'",
    ],
    # 34. Josko Services
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Josko Services (Josko LLC)",
        "HVAC / Multi-Trade",
        "Apopka, FL",
        "Open 24 Hours",
        "Carlos Rivera (President) / Chris Risi (GM)",
        "CAC1819201",
        "(407) 807-0337",
        "(407) 807-0337",
        "info@joskoservices.com",
        "https://joskoservices.com",
        "Yes",
        "4.5 (436 reviews)",
        "24/7 service. 436 reviews across I-4 corridor. Tech dispatch routing and automated booking intake.",
        "",
        "",
        "",
        "$8,500",
        "Ask for Carlos Rivera or Chris Risi: 'Hey Chris, our LiveWire dashboard routes emergency calls directly to on-call techs.'",
    ],
    # 35. Sky AC Repair Apopka
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Sky AC Repair Apopka",
        "HVAC",
        "Apopka, FL",
        "Open 24 Hours",
        "Jorge A. Santana (Owner / Operator)",
        "CAC1824102",
        "(689) 910-1029",
        "(689) 910-1029",
        "service@skyacapopka.com",
        "https://skyacapopka.com",
        "Yes",
        "5.0 (2 reviews)",
        "24/7 service. Brand new local operator needing instant missed-call capture and review generation.",
        "",
        "",
        "",
        "$5,000",
        "Ask for Jorge: 'Hey Jorge, we help new HVAC owners in Apopka automatically collect 5-star Google reviews after every job.'",
    ],
    # 36. JD'S Heating & Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "JD'S Heating & Air Conditioning Inc.",
        "HVAC",
        "Casselberry, FL",
        "Closes 5:00 PM",
        "Michael Charles Tenda (Primary Qualifier / President)",
        "CAC1813459",
        "(407) 699-9530",
        "(407) 699-9530",
        "service@jdsheatandair.com",
        "https://jdsheatandair.com",
        "Yes",
        "4.9 (482 reviews)",
        "Closes 5 PM. 15+ years established name. 482 reviews. After-hours missed call capture.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Michael Tenda: 'Hey Michael, saw you close at 5 in Casselberry—we catch all evening emergency system replacement calls.'",
    ],
    # 37. Keeping it Cool HVAC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Keeping it Cool HVAC LLC",
        "HVAC",
        "Winter Garden / Apopka, FL",
        "Open 24 Hours",
        "Ronaldo Guarionex Alcantara (Owner / Qualifier)",
        "CAC1822915",
        "(407) 401-8773",
        "(407) 401-8773",
        "contact@keepingitcoolhvac.com",
        "https://keepingitcoolhvac.com",
        "Yes",
        "5.0 (126 reviews)",
        "24/7 service. 126 5-star reviews. Rapid response focus—convert on-call emergency inquiries instantly.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Ronaldo: 'Hey Ronaldo, saw your 126 5-star reviews in Winter Garden—our system texts missed callers within 3 seconds.'",
    ],
    # 38. Florida Longwood Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Florida Longwood Air Conditioning And Heating",
        "HVAC",
        "Longwood, FL",
        "Open 24 Hours",
        "David E. Harrison (Owner / Qualifier)",
        "CAC1821440",
        "(407) 809-3234",
        "(407) 809-3234",
        "info@longwoodflhvac.com",
        "https://longwoodflhvac.com",
        "Yes",
        "5.0 (5 reviews)",
        "24/7 service. Local boutique shop needing automated speed-to-lead and review booster.",
        "",
        "",
        "",
        "$5,000",
        "Ask for David: Pitch instant text recovery + automatic Google review booster.",
    ],
    # 39. Immaculate Air
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Immaculate Air",
        "HVAC",
        "Altamonte Springs, FL",
        "Open 24 Hours",
        "Nelson E. Hernandez (President / Qualifier)",
        "CAC1820885",
        "(321) 888-6121",
        "(321) 888-6121",
        "service@immaculateairfl.com",
        "https://immaculateairfl.com",
        "Yes",
        "5.0 (12 reviews)",
        "24/7 service. 5-star reputation. Owner-operator sweet spot for high-touch automated booking.",
        "",
        "",
        "",
        "$5,500",
        "Ask for Nelson: Pitch after-hours priority intake form and instant text back.",
    ],
    # 40. Cool It Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Cool It Air Conditioning Repair and Installation",
        "HVAC",
        "Zellwood / Apopka, FL",
        "Open 24 Hours",
        "Neil M. Condon (Manager / Qualifier)",
        "CAC1819342",
        "(954) 953-2947",
        "(954) 953-2947",
        "service@coolithvacfl.com",
        "https://coolithvacfl.com",
        "Yes",
        "5.0 (47 reviews)",
        "24/7 service. 10+ years in trade. Sweet spot for missed-call recovery during hot afternoon calls.",
        "",
        "",
        "",
        "$6,500",
        "Ask for Neil Condon: 'Hey Neil, we help Zellwood/Apopka contractors catch emergency calls while they are on service jobs.'",
    ],
    # 41. A.M.S. Cooling & Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "A.M.S. Cooling & Heating LLC",
        "HVAC / Electrical",
        "Clermont / Central FL",
        "Open 24 Hours",
        "Christopher Brijbasu / Raul Sanchez (Managers / Qualifiers)",
        "CAC1822340",
        "(321) 527-6978",
        "(321) 527-6978",
        "info@amscoolingfl.com",
        "https://amscoolingfl.com",
        "Yes",
        "5.0 (32 reviews)",
        "24/7 service. Dual HVAC + electrical services. Missed call text back recovers $8k+ system swaps.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Christopher or Raul: 'Hey Raul, we help dual HVAC/electric contractors catch high-ticket emergency inquiries.'",
    ],
    # 42. Frozen Air Cooling and Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Frozen Air Cooling and Heating",
        "HVAC",
        "Orlando / Apopka, FL",
        "Closes 6:00 PM",
        "Alexander J. Vega (Owner / Qualifier)",
        "CAC1823790",
        "(689) 275-3663",
        "(689) 275-3663",
        "info@frozenairhvac.com",
        "https://frozenairhvac.com",
        "Yes",
        "4.9 (29 reviews)",
        "Closes 6 PM. Fast-growing shop needing automated after-hours capture and review acceleration.",
        "",
        "",
        "",
        "$6,000",
        "Ask for Alexander Vega: 'Hey Alexander, saw you close at 6 in Orlando—we turn evening missed calls into booked morning jobs.'",
    ],
    # 43. Scott's Heating & Air Conditioning
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Scott's Heating & Air Conditioning LLC",
        "HVAC",
        "Longwood, FL",
        "Closes 9:00 PM",
        "Randolph Scott Moist (President / Primary Qualifier)",
        "CAC1816941",
        "(407) 513-4406",
        "(407) 513-4406",
        "service@scottsair.com",
        "https://scottsair.com",
        "Yes",
        "4.7 (639 reviews)",
        "Closes 9 PM. 25+ years in business. 639 reviews. High ad spend across Seminole County.",
        "",
        "",
        "",
        "$9,000",
        "Ask for Scott Moist: 'Hey Scott, with 600+ reviews in Longwood, our LiveWire module catches callers who drop off on busy lines.'",
    ],
    # 44. Swift Brothers Plumbing, Heating & Air
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Swift Brothers Plumbing, Heating & Air",
        "HVAC / Plumbing",
        "Apopka / Orlando, FL",
        "Open 24 Hours",
        "Eric Swift / Scott Swift (Managers)",
        "CAC1819230",
        "(407) 259-4320",
        "(844) 396-9662",
        "info@swiftbrothers.com",
        "https://swiftbrothers.com",
        "Yes",
        "4.3 (220 reviews)",
        "24/7 service. 4.3 rating with active sponsored ads. Need review boost to climb to 4.8+ and missed-call safety net.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Eric or Scott: 'Hey Eric, pitch review generation to push your rating from 4.3 to 4.8+ and stop missed ad call leak.'",
    ],
    # 45. Enginair Air & Refrigeration
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Enginair Air & Refrigeration LLC",
        "HVAC / Refrigeration",
        "Montverde, FL",
        "Open 24 Hours",
        "Jamie Gomperts (President) / Edward Gomperts Jr.",
        "CAC1820615",
        "(407) 544-2113",
        "(407) 544-2113",
        "service@enginairfl.com",
        "https://enginairfl.com",
        "Yes",
        "4.9 (240 reviews)",
        "24/7 service. 7+ years in business. Full maintenance and replacement specialist in Lake County.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Jamie Gomperts: 'Hey Jamie, we help Montverde and Lake County contractors lock down emergency AC calls immediately.'",
    ],
    # 46. Diamond Air Conditioning And Heating
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Diamond Air Conditioning And Heating LLC",
        "HVAC",
        "Orlando, FL",
        "Closes 5:00 PM",
        "Samer Hassan / Samuel Coker (Authorized Members / Qualifiers)",
        "CAC1823992",
        "(689) 261-6914",
        "(689) 261-6914",
        "info@diamondairfl.com",
        "https://diamondairfl.com",
        "Yes",
        "4.6 (247 reviews)",
        "Closes 5 PM. Active Google presence. Recapture evening and weekend emergency HVAC calls.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Samer Hassan: 'Hey Samer, saw you close at 5 in Orlando—we capture all evening emergency replacement dials.'",
    ],
    # 47. Heating & Cooling | Mafer AC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Heating & Cooling | Mafer AC",
        "HVAC",
        "Orlando, FL",
        "Closes 6:00 PM",
        "Luis Enrique Quintero (Owner / Certified Qualifier)",
        "CAC1822076",
        "(407) 632-3620",
        "(407) 632-3620",
        "contact@maferac.com",
        "https://maferac.com",
        "Yes",
        "5.0 (405 reviews)",
        "Closes 6 PM. 5.0 rating with 405 reviews. 24-hr install turnaround promise—prime candidate for automated intake.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Luis Quintero: 'Hey Luis, with 400 5-star reviews, our 3-second text-back locks down emergency AC changeouts instantly.'",
    ],
    # 48. A/C HVAC and Air Conditioning Experts
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "A/C HVAC and Air Conditioning Experts Orlando",
        "HVAC",
        "Orlando, FL",
        "Open 24 Hours",
        "Carlos E. Mendez (Owner / Qualifier)",
        "CAC1819445",
        "(689) 208-4434",
        "(689) 208-4434",
        "info@orlandohvacexperts.com",
        "https://orlandohvacexperts.com",
        "Yes",
        "5.0 (72 reviews)",
        "24/7 service. 15+ years in business. Sweet-spot owner operator with 72 5-star reviews.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Carlos Mendez: 'Hey Carlos, we help Orlando HVAC operators catch every missed call while on job sites.'",
    ],
    # 49. Kurt's AC & Heat
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Kurt's AC & Heat",
        "HVAC",
        "Tavares, FL",
        "Closes 5:00 PM",
        "Kurt E. Schneider (Owner / Primary Qualifier)",
        "CAC1815890",
        "(352) 343-1755",
        "(352) 343-1755",
        "info@kurtsacandheat.com",
        "https://www.kurtsacandheat.com",
        "Yes",
        "4.9 (406 reviews)",
        "Closes 5 PM. 35+ years in business. 406 reviews. High past customer volume for seasonal RevSurge campaigns.",
        "",
        "",
        "",
        "$8,000",
        "Ask for Kurt Schneider: 'Hey Kurt, 35 years in Tavares means a huge customer list—our RevSurge engine turns that into $25k in booked tune-ups.'",
    ],
    # 50. Top Tier Cooling
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Top Tier Cooling",
        "HVAC",
        "Orlando, FL",
        "Open 24 Hours",
        "Jayson Javier Castanon (Qualifier) / Keenan Harris (CEO)",
        "CAC1824593",
        "(407) 449-7333",
        "(407) 236-3582",
        "info@toptier-cooling.com",
        "https://toptier-cooling.com",
        "Yes",
        "4.9 (63 reviews)",
        "Running Google LSA ads. Claims 24/7 emergency service with 63 reviews. Perfect owner-operator candidate for instant missed-call capture.",
        "",
        "",
        "",
        "$7,500",
        "Ask for Jayson or Keenan: 'Hey Jayson, it's regarding your emergency text-back setup in Orlando.'",
    ],
    # 51. Arctic Air Temp
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Arctic Air Temp",
        "HVAC / Plumbing",
        "Orlando / Kissimmee, FL",
        "Open 24 Hours",
        "Fayfat Dias (Primary Licensee / Owner)",
        "CAC1822832 / CFC1432906",
        "(407) 401-8888",
        "(407) 401-8888",
        "info@arcticairtemp.com",
        "https://arcticairtemp.com",
        "Yes",
        "5.0 (237 reviews)",
        "Google LSA badge shows 'Typically replies in 30 min'. During emergency calls, 30 min is too slow—LeadNet fires in 3 seconds.",
        "",
        "",
        "",
        "$8,500",
        "Ask for Fayfat: 'Hey Fayfat, I saw Google tells customers you reply in 30 mins—we can make that 3 seconds so you never lose an emergency swap.'",
    ],
    # 52. The Right Service
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "The Right Service",
        "HVAC",
        "Orlando, FL",
        "Open 24 Hours",
        "Roland Rodriguez / Blanca Ramirez (Officers)",
        "CAC1818721",
        "(561) 814-1600",
        "(561) 814-1600",
        "support@therightservicefl.com",
        "https://therightservicefl.com",
        "Yes",
        "4.4 (83 reviews)",
        "4.4 rating + 83 reviews. Needs automated 5-star Google review requests after service + missed-call text back.",
        "",
        "",
        "",
        "$6,500",
        "Ask for Roland: Pitch instant call-recovery + automatic Google Review generation.",
    ],
    # 53. Hurricane Air Duct Cleaning & HVAC
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Hurricane Air Duct Cleaning & HVAC",
        "HVAC / Ducting",
        "Orlando, FL",
        "Closes 8:00 PM",
        "Joshua P. Bertocci (Manager / Owner)",
        "CAC1820119",
        "(941) 282-7797",
        "(941) 282-7797",
        "customercare@hurricaneairductcleaning.com",
        "https://hurricaneairductcleaning.com",
        "Yes",
        "4.9 (572 reviews)",
        "LSA badge shows 'Typically replies in a few hours'. Open until 8 PM. Missing high-ticket weekend replacement leads.",
        "",
        "",
        "",
        "$5,500",
        "Ask for Joshua: Pitch weekend and evening automated text back.",
    ],
    # 54. Air-Tech Mechanical
    [
        "Not Contacted",
        "A - High (Sweet Spot / Fast Conversion)",
        "Air-Tech Mechanical",
        "HVAC",
        "Orlando, FL",
        "Open 24 Hours",
        "Walter Joseph (Authorized Member / Manager)",
        "CAC1819744",
        "(407) 874-7351",
        "(561) 889-0755",
        "service@myairtechmechanical.com",
        "https://myairtechmechanical.com",
        "Yes",
        "4.9 (291 reviews)",
        "5+ years in business, 24/7 emergency service ad. 291 reviews. Strong local operator.",
        "",
        "",
        "",
        "$7,000",
        "Ask for Walter: Pitch 24/7 on-call tech alert + instant customer intake link.",
    ],
    # 55. Ratti Air and Heat
    [
        "Follow-up",
        "A - High (Sweet Spot / Fast Conversion)",
        "Ratti Air and Heat",
        "HVAC",
        "Orlando / Brevard, FL",
        "Closes 11:59 PM",
        "Gino A. Ratti III (President / Primary Qualifier)",
        "CAC1817290",
        "(321) 360-2798",
        "(321) 360-2798",
        "Office@RattiAirandHeat.com",
        "https://www.rattiairandheat.com",
        "Yes",
        "5.0 (772 reviews)",
        "772 reviews, open until 11:59 PM. High volume emergency calls.",
        "Called yesterday. Follow-up pending.",
        "",
        "",
        "$8,000",
        "Ask for Gino: FOLLOW-UP dial. If voicemail, send text hook immediately.",
    ],
]

# 1. Write CSV
with open(csv_path, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    writer.writerows(companies_data)

print(f"Wrote {len(companies_data)} rows to CSV: {csv_path}")

# 2. Write formatted Excel (.xlsx)
def create_excel(target_path):
    try:
        workbook = xlsxwriter.Workbook(target_path)
        ws = workbook.add_worksheet("Hitlist Pipeline")

        color_dark = "#090d16"
        color_border = "#334155"

        title_fmt = workbook.add_format({
            "bold": True,
            "font_size": 14,
            "font_color": "#22d3ee",
            "bg_color": color_dark,
            "align": "left",
            "valign": "vcenter",
            "font_name": "Segoe UI",
        })

        metric_card_fmt = workbook.add_format({
            "bold": True,
            "font_size": 10,
            "font_color": "#ffffff",
            "bg_color": "#1e293b",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": color_border,
            "font_name": "Segoe UI",
        })

        metric_num_fmt = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "font_color": "#22d3ee",
            "bg_color": "#0f172a",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": color_border,
            "font_name": "Segoe UI",
        })

        header_fmt = workbook.add_format({
            "bold": True,
            "font_size": 10,
            "font_color": "#000000",
            "bg_color": "#22d3ee",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#0891b2",
            "text_wrap": True,
            "font_name": "Segoe UI",
        })

        data_fmt = workbook.add_format({
            "font_size": 10,
            "font_color": "#1e293b",
            "bg_color": "#ffffff",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#e2e8f0",
            "font_name": "Segoe UI",
        })

        alt_data_fmt = workbook.add_format({
            "font_size": 10,
            "font_color": "#1e293b",
            "bg_color": "#f8fafc",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#e2e8f0",
            "font_name": "Segoe UI",
        })

        hours_fmt = workbook.add_format({
            "font_size": 10,
            "font_color": "#0369a1",
            "bg_color": "#f0f9ff",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#bae6fd",
            "font_name": "Segoe UI",
            "bold": True,
        })

        hours_247_fmt = workbook.add_format({
            "font_size": 10,
            "font_color": "#047857",
            "bg_color": "#ecfdf5",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#a7f3d0",
            "font_name": "Segoe UI",
            "bold": True,
        })

        status_booked_fmt = workbook.add_format({
            "font_size": 10,
            "bold": True,
            "font_color": "#065f46",
            "bg_color": "#d1fae5",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#a7f3d0",
            "font_name": "Segoe UI",
        })

        status_gatekeeper_fmt = workbook.add_format({
            "font_size": 10,
            "bold": True,
            "font_color": "#92400e",
            "bg_color": "#fef3c7",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#fde68a",
            "font_name": "Segoe UI",
        })

        status_disqualified_fmt = workbook.add_format({
            "font_size": 10,
            "bold": True,
            "font_color": "#991b1b",
            "bg_color": "#fee2e2",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#fca5a5",
            "font_name": "Segoe UI",
        })

        status_followup_fmt = workbook.add_format({
            "font_size": 10,
            "bold": True,
            "font_color": "#1e40af",
            "bg_color": "#dbeafe",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#bfdbfe",
            "font_name": "Segoe UI",
        })

        # Summary Dashboard Header in Row 1 (A1:T1)
        ws.merge_range("A1:T1", "INTENT LEADNET - VERIFIED FLORIDA DBPR & SUNBIZ HITLIST", title_fmt)
        ws.set_row(0, 32)

        # KPI Summary Cards (Rows 3-4)
        ws.merge_range("A3:B3", "QUALIFIED PROSPECTS", metric_card_fmt)
        ws.merge_range("A4:B4", '=COUNTA(C7:C300)', metric_num_fmt)

        ws.merge_range("C3:D3", "TIER A SWEET SPOT", metric_card_fmt)
        ws.merge_range("C4:D4", '=COUNTIF(B7:B300, "A*")', metric_num_fmt)

        ws.merge_range("E3:F3", "DEMOS BOOKED", metric_card_fmt)
        ws.merge_range("E4:F4", '=COUNTIF(A7:A300, "Demo Booked")', metric_num_fmt)

        ws.merge_range("G3:H3", "CALLS MADE", metric_card_fmt)
        ws.merge_range("G4:H4", '=COUNTIF(A7:A300, "<>Not Contacted") - COUNTBLANK(A7:A300)', metric_num_fmt)

        ws.merge_range("I3:J3", "ACTIVE PIPELINE", metric_card_fmt)
        ws.merge_range("I4:J4", '=COUNTIF(A7:A300, "Gatekeeper*") + COUNTIF(A7:A300, "Follow-up")', metric_num_fmt)

        # Table Header on Row 6 (Index 5)
        ws.set_row(5, 28)
        for col_idx, header in enumerate(headers):
            ws.write(5, col_idx, header, header_fmt)

        # Populate Data
        for row_idx, row_data in enumerate(companies_data):
            excel_row = 6 + row_idx
            ws.set_row(excel_row, 22)
            is_alt = (row_idx % 2 == 1)
            row_fmt = alt_data_fmt if is_alt else data_fmt

            for col_idx, cell_value in enumerate(row_data):
                # Status formatting (Col A)
                if col_idx == 0:
                    status = str(cell_value)
                    if "Booked" in status:
                        ws.write(excel_row, col_idx, cell_value, status_booked_fmt)
                    elif "Gatekeeper" in status:
                        ws.write(excel_row, col_idx, cell_value, status_gatekeeper_fmt)
                    elif "Disqualified" in status or "Do Not Call" in status:
                        ws.write(excel_row, col_idx, cell_value, status_disqualified_fmt)
                    elif "Follow-up" in status:
                        ws.write(excel_row, col_idx, cell_value, status_followup_fmt)
                    else:
                        ws.write(excel_row, col_idx, cell_value, row_fmt)
                # Store Hours formatting (Col F / Col idx 5)
                elif col_idx == 5:
                    hours_str = str(cell_value)
                    if "24" in hours_str:
                        ws.write(excel_row, col_idx, cell_value, hours_247_fmt)
                    else:
                        ws.write(excel_row, col_idx, cell_value, hours_fmt)
                else:
                    ws.write(excel_row, col_idx, cell_value, row_fmt)

        # Set Column Widths
        col_widths = [
            18,  # Status (0 / A)
            22,  # Priority Tier (1 / B)
            28,  # Company Name (2 / C)
            14,  # Trade (3 / D)
            18,  # City / Metro (4 / E)
            18,  # Store / Operating Hours (5 / F)
            32,  # Verified Licensee / Owner (6 / G)
            18,  # State License # (7 / H)
            18,  # Direct / Cell Phone (8 / I)
            18,  # Office / LSA Phone (9 / J)
            26,  # Email (10 / K)
            28,  # Website (11 / L)
            14,  # Running Google Ads? (12 / M)
            16,  # Google Rating / Reviews (13 / N)
            40,  # Speed to Lead Hook (14 / O)
            18,  # Dial 1 Outcome (15 / P)
            18,  # Dial 2 Outcome (16 / Q)
            18,  # Demo Booked Date (17 / R)
            14,  # Est. System Value (18 / S)
            45,  # Notes / Next Action (19 / T)
        ]

        for col_idx, width in enumerate(col_widths):
            ws.set_column(col_idx, col_idx, width)

        # Data Validation Dropdowns
        ws.data_validation(
            6, 0, 5 + len(companies_data), 0,
            {
                "validate": "list",
                "source": [
                    "Not Contacted",
                    "Called - No Answer",
                    "Gatekeeper / Callback",
                    "Voicemail + SMS Sent",
                    "Follow-up",
                    "Demo Booked",
                    "Closed Won",
                    "Disqualified / Do Not Call",
                ],
            }
        )

        ws.data_validation(
            6, 1, 5 + len(companies_data), 1,
            {
                "validate": "list",
                "source": [
                    "A - High (Sweet Spot / Fast Conversion)",
                    "B - Medium (Commercial / Multi-Tech)",
                    "C - Low / Disqualified",
                ],
            }
        )

        ws.data_validation(
            6, 12, 5 + len(companies_data), 12,
            {"validate": "list", "source": ["Yes", "Yes (Sponsored)", "No"]}
        )

        # Freeze Panes at Row 6 and Column C (Company Name remains anchored)
        ws.freeze_panes(6, 3)

        workbook.close()
        print(f"Successfully wrote formatted Excel to {target_path}")
    except Exception as e:
        print(f"Could not write to {target_path}: {e}")

# Generate all configured target spreadsheets
for path in xlsx_paths:
    create_excel(path)
